title: My Awesome Page!
author: Dan Barrick
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My awesome new site is just one of many incredible creations and projects that I will be running and owning. Come back for more as I progress on my coding journey!

# social links
twitter_username: your-twitter-handle
github_username:  dream-ardor

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
