title: Dan's Awesome Site
author: Dan Barrick
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to Dan's incredible new website. I plan to dominate, create and educate. Come back soon and check out my fresh new content and be amazed!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
